# Generated by Django 4.2.5 on 2023-09-25 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion_hito2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
